#!/bin/bash

set -x
set -e
 
pkg=libspdlog-dev
if [ "$AUTOPKGTEST_TMP" = "" ] ; then
  AUTOPKGTEST_TMP=`mktemp -d /tmp/${pkg}-test.XXXXXX`
  trap "rm -rf $AUTOPKGTEST_TMP" 0 INT QUIT ABRT PIPE TERM
fi
cd $AUTOPKGTEST_TMP

cp -r /usr/share/doc/libspdlog-dev/tests/ .
mkdir cmake
cp /usr/share/doc/libspdlog-dev/utils.cmake cmake/
cd tests
for file in *.gz; do gunzip ${file}; done
cmake -DSPDLOG_BUILD_TESTS=ON -DSPDLOG_BUILD_TESTS_HO=ON -DSPDLOG_FMT_EXTERNAL=ON .
make CFLAGS=-DSPDLOG_FMT_EXTERNAL spdlog-utests-ho spdlog-utests
make test
